### ISSUE TITLE
ui: account page > linked accounts button arrow under text

### ISSUE THREAD

**Issue by sbolel** [prescottprue/devshare-site#48]
https://www.pivotaltracker.com/story/show/141478437

<img width="636" alt="screen shot 2017-03-10 at 12 13 02 am" src="https://cloud.githubusercontent.com/assets/1915925/23784234/70faf7c4-0526-11e7-9968-7cad7a079f45.png">

**Comment by prescottprue** [comment]
Yup, seen this one. I think it is due to the `material-ui` list item and the scss class that is applied to it

**Comment by sbolel** [comment]
# 🏅
